# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
weight = 2
name = "Services"
hasChildren = true
[main.params]
isMenuLarge = true

[[main]]
parent = "Services"
name = "Managed Security"
pre = "<i class='dropdown-icon fas fa-shield-alt'></i>"
post = "<small class='dropdown-subtitle'>Security as a service.</small>"
url = "/services/managed-security"
weight = 1

[[main]]
parent = "Services"
name = "Zero Trust Network Access"
pre = "<i class='dropdown-icon fas fa-network-wired'></i>"
post = "<small class='dropdown-subtitle'>Zero trust network access.</small>"
url = "/services/zero-trust-network-access"
weight = 2

[[main]]
parent = "Services"
name = "vCISO Services"
pre = "<i class='dropdown-icon fas fa-laptop-house'></i>"
post = "<small class='dropdown-subtitle'>Application built to improve productivity.</small>"
url = "/services/vCISO-services"
weight = 3

[[main]]
parent = "Services"
name = "Security Consulting"
pre = "<i class='dropdown-icon fas fa-chart-line'></i>"
post = "<small class='dropdown-subtitle'>Create custom reports from any data set.</small>"
url = "/services/security-consulting"
weight = 4

[[main]]
weight = 3
name = "Blog"
url = "/blog"

[[main]]
weight = 4
name = "Company"
hasChildren = true

[[main]]
parent = "Company"
name = "About"
url = "/about"
weight = 1


[[main]]
parent = "Company"
name = "Values"
url = "/values"
weight = 8

[[main]]
parent = "Company"
name = "Career"
url = "/career"
weight = 9


[[main]]
name = "Contact"
url = "/contact"
weight = 30

# footer menu left
[[footer_left]]
name = "About Us"
url = "/about"
weight = 1

[[footer_left]]
name = "Values"
url = "/values"
weight = 3

[[footer_left]]
name = "Career"
url = "/career"
weight = 4


# footer menu middle
[[footer_middle]]
name = "Managed Security"
url = "/services/managed-security"
weight = 1

[[footer_middle]]
name = "Zero Trust Network Access"
url = "/services/zero-trust-network-access"
weight = 2

[[footer_middle]]
name = "vCISO Services"
url = "/services/vCISO-services"
weight = 3

[[footer_middle]]
name = "Security Consulting"
url = "/services/security-consulting"
weight = 4

# footer menu right
[[footer_right]]
name = "Customer Portal"
url = "/faq"
weight = 1

[[footer_right]]
name = "Legal"
url = "/legal"
weight = 2

[[footer_right]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3

[[footer_right]]
name = "Security"
url = "/security"
weight = 4
